### ISSUE TITLE
Buzzik Logo

### ISSUE THREAD

**Issue by cooperpellaton** [GT-Buzzik/Lambda-API#2]

**Comment by JacksonVance** [comment]
![buzziklogofirstdraft](https://user-images.githubusercontent.com/15204258/45163869-45a34d00-b1bf-11e8-9c11-ea07b7487e78.png)

**Comment by thatcherfreeman** [comment]
Reopened due to aliasing along right margin.

**Comment by JacksonVance** [comment]
The updated logo has been updated, please check for aliasing.

**Comment by cooperpellaton** [comment]
Final file is located in Google Drive.
